sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
branches:
  only:
    - hexo # build master branch only
before_install:
  - cd blog
  - npm install hexo-cli -g
  - npm install
script:
  - hexo clean
  - hexo generate # generate static files
after_script:
  - cd ./public
  - git init
  - git config user.name "NightCandle"
  - git config user.email "instkffff@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master