
# html lang
language: zh

# main menu navigation
menu:
  Home: /

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap # for font
- https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.css # for toc basic style
- https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@200;300;400;500;600;700;900&display=swap

# scripts loaded in the end of the body
scripts_defer:
# https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
- /js/paper.js # for basic script


social:
  Twitter: https://twitter.com/_NightCandle
  Mail: mailto:instkffff@gmail.com
  # and more, you can add other link by the same way

# Uncomment to disable sidebar
# toc: false
# link: false
archives: false
# categories: false
# tags: false
# theme color
main_color: NightCandle # forest | grass | sky | sun | sea | default | NightCandle

# google Analytics
# google_analytics_id: xx-xxxxxxx-xx

# commend module
comment:
  enable: true
  appId: gCDQYqpdRPLt6gik2cBI8hbI-gzGzoHsz
  appKey: R3yDLDvwOoagPzxudAFiRtwa
  placeholder: say something
  notify: false
  verify: false
  avatar: 
